In [11]:
import re

In [23]:
bag_possibilities={}

with open('input_day7.txt', 'r') as f:
    for line in f.readlines():
        line=line.strip()
        
        top= line.split('bags contain')[0].strip()
        
        tmp= [ bag.strip().strip('.') for bag in line.split('bags contain')[1].strip().split(',') ]
        contains=[]
        for i in tmp:
            m=re.search('(\d+) (.*) bag',i)
            if m is not None:
                contains.append((int(m.groups()[0]),
                                 m.groups()[1],
                                ))
            
        
        bag_possibilities[top] = contains

In [42]:
def can_contain_gold(contain_list):
    if len(contain_list) == 0:
        return False
    colors = [i[1] for i in contain_list]
    
    if 'shiny gold' in colors:
        return True
    else:
        return any([ can_contain_gold(bag_possibilities[color]) for color in colors])
        

In [45]:
sum([ can_contain_gold(contents) for color, contents in bag_possibilities.items()])

213

In [48]:
bag_possibilities['shiny gold']

[(2, 'pale blue'), (1, 'clear black'), (2, 'wavy teal'), (3, 'dotted red')]

In [58]:
def sum_bags_inside(contain_list):
    if len(contain_list) == 0:
        return 0

    return sum( [ num*(1+sum_bags_inside(bag_possibilities[color])) for num,color in contain_list] )

In [59]:
sum_bags_inside(bag_possibilities['shiny gold'])

38426

# Day 8

In [1]:
instructions=[]

with open('input_day8.txt', 'r') as f:
    for line in f.readlines():
        line=line.strip()
        i,j = line.split(' ')
        
        instructions.append((i, int(j)))
        


In [2]:
idx = 0
acc = 0
visted_idx = []

while idx not in visted_idx:
    visted_idx.append(idx)
    code, val = instructions[idx]
    if code == 'acc':
        acc+= val
        idx+= 1

    elif code == 'jmp':
        idx+= val
        
    else:
        idx +=1
        
    
    

print(acc)

1671


In [3]:
len(visted_idx)

217

In [4]:
possible_changes = [idx for idx in visted_idx if instructions[idx][0] in ['jmp', 'nop']]

In [5]:
len(possible_changes)

95

In [12]:
change = {'nop': 'jmp',
          'jmp': 'nop',
         }
for test in possible_changes:
    tmp_instruct = instructions.copy()
    tmp_instruct[test] = (change[tmp_instruct[test][0]],tmp_instruct[test][1])
    
    acc=0
    visited=[]
    idx=0
    
    while idx not in visited and idx < len(instructions):
        visited.append(idx)
        code, val = tmp_instruct[idx]
        if code == 'acc':
            acc+= val
            idx+= 1
    
        elif code == 'jmp':
            idx+= val
            
        else:
            idx +=1
            
    if idx == len(instructions):
        print(f'value is {acc}')
        

value is 892


In [15]:
tmp=[1,2, 0]

In [18]:
tmp.sort(reverse=True)

In [19]:
tmp

[2, 1, 0]

In [22]:
i = 0
while tmp[i] > 1:
    i+=1
print(i)

1


# Day 9

In [13]:
numbers=[]

with open('input_day9.txt', 'r') as f:
    for line in f.readlines():
        numbers.append(int(line.strip()))
        


In [46]:
def binary_search(val, int_1, num_list):
    if len(num_list) == 1:
        return int_1 + num_list[0] ==val
    
    idx = len(num_list)//2
    int_2 = num_list[idx]
    int_sum = int_1+int_2
    if int_sum == val :
        return True
    elif int_sum > val:
        if idx+1 == len(num_list):
            return False
        return binary_search(val, int_1, num_list[idx+1:])
    else:
        return binary_search(val, int_1, num_list[0:idx])

def check_if_sum(val, num_list):
    tmp_list = num_list.copy()
    tmp_list.sort(reverse=True)
    i=0
    while tmp_list[i] > val: 
        i+=1
    tmp_list = tmp_list[i:]
    for i in range(len(tmp_list)-1):
        check=binary_search(val,tmp_list[i], tmp_list[i+1:])
        if check:
            return check
    return False
    

In [40]:
check_if_sum(numbers[25], numbers[0:25])

True

In [47]:
for num in range(25, len(numbers)):
    val = numbers[num]
    num_list = numbers[num-25:num]
    if not check_if_sum(val, num_list):
        print(val)
        break

20874512


In [55]:
needed_sum = 20874512
for i in range(0,len(numbers)):
    j=i+1
    while sum(numbers[i:j]) < needed_sum:
        j+=1
        
    if sum(numbers[i:j]) == needed_sum:
        subset=numbers[i:j]
        print(subset)
        print(subset[0]+subset[-1])
        break
    

[925549, 966007, 1012779, 1054812, 1220613, 1147519, 1158705, 1163492, 1204640, 1209427, 1215826, 1227012, 1231799, 1344496, 1349283, 1355682, 2086871]
3012420


In [51]:
len(numbers)

1000

# Day 10

In [21]:
import numpy as np

In [27]:
jolts=[]

with open('input_day10.txt', 'r') as f:
    for line in f.readlines():
        jolts.append(int(line.strip()))
jolts.append(0)        


In [28]:
jolts.sort()

In [29]:
jolts.append(jolts[-1]+3)
jolts = np.asarray(jolts)

In [30]:
diffs = jolts[1:] - jolts[0:-1]

In [31]:
sum(diffs == 1)*sum(diffs == 3)

2112

In [32]:
diffs

array([1, 1, 1, 3, 1, 1, 1, 3, 1, 1, 3, 1, 1, 3, 1, 1, 1, 3, 1, 1, 1, 1,
       3, 1, 1, 3, 1, 1, 1, 3, 1, 1, 1, 3, 3, 1, 3, 1, 1, 1, 1, 3, 1, 1,
       1, 3, 3, 3, 1, 1, 1, 1, 3, 1, 1, 1, 3, 3, 1, 1, 1, 1, 3, 1, 3, 3,
       3, 1, 1, 3, 3, 1, 1, 1, 1, 3, 1, 1, 3, 1, 1, 1, 1, 3, 1, 3, 3, 3,
       1, 1, 1, 1, 3, 1, 1, 1, 1, 3])

In [81]:
test_str = str(diffs).replace('3', '|').replace(' ','').replace('\n','').replace('[','|').replace(']','|').replace('|','||')

In [ ]:
# 11 = 2
# 111 = 4
# 1111 = 7

In [44]:
import re

In [82]:
test_str

'||111||111||11||11||111||1111||11||111||111||||1||1111||111||||||1111||111||||1111||1||||||11||||1111||11||1111||1||||||1111||1111||||'

In [83]:
pow_2 = len(re.findall('(\|11\|)', test_str))
pow_4 = len(re.findall('(\|111\|)', test_str))
pow_7 = len(re.findall('(\|1111\|)', test_str))

In [84]:
np.power(2,pow_2)*np.power(4,pow_4)*np.power(7,pow_7)

3022415986688

# Day 11

In [1]:
import numpy as np

In [2]:
seats=[]

with open('input_day11.txt', 'r') as f:
    for line in f.readlines():
        seats.append(list(line.strip()))


In [3]:
seats = np.asarray(seats)

In [4]:
c = len(seats[0])
r = len(seats)

In [37]:
def count_unoccupied(curr_map, next_map, pos):
    state = curr_map[(pos)]
    n_occ = sum([ curr_map[(pos[0]+i,pos[1]+j) ]=='#'  
                  for i in [-1, 0, 1]
                  for j in  [-1, 0, 1]
                  if  (pos[0]+i  >= 0 and pos[0]+i  <  r
                       and not (i ==j == 0) and 
                       pos[1]+j  >= 0 and pos[1]+j  <  c)
                ])
    
    if state == 'L' and n_occ == 0 :
            next_map[pos] = "#"
            
    if state == '#' and n_occ >=4:
            next_map[pos] = "L"
            
    return next_map
        
cur_map = seats.copy()
diff=1
#for i in range(4):
iteration = 0
while diff != 0 and iteration < 500:
    next_map = cur_map.copy()
    for row in range(r):
        for col in range(c):
            if cur_map[(row,col)] == '.':
                continue
            next_map = count_unoccupied(cur_map, next_map, (row,col))
            
    diff = (next_map != cur_map).sum()
    iteration +=1
    cur_map = next_map.copy()
            

In [38]:
iteration

86

In [39]:
print(diff)

0


In [40]:
for i in cur_map:
    print(''.join(i))


#L#L#L#L.L#L#.#L#L#.#L#L#L##L#L#L#.#L#L#L##L#L#L#.#L#L#.#L#L#L#L#L##L#.#L#L#L#.#L#L#L.L#L#L#L#L#.#
LLLLLLLL#LLL#L#LLLL.L.LL.LLL.LLLLL.LLLLLL##LLL.LL.LLLLL.LLLLLLLL.LLLLLLLLL.LLL.LLLLLL#L#LLLLLLLLLL
#L#L#L#L#L#LL.LL##L##L#L#L##.#L.L#.#L#L#LL.LLL#L#.#L#L#L#L#.L#L#.#L#L#.#L#L#L#.#L#L#L.LLL#L#L#L#L#
LLLLLLLL.LLL#.#L#LL..LLLLLLL.L.#L#.LLLL#L#.#L#LLL.LLLLL.LLLLLLLL.LLLLLL#L#L#L#.LLLLLL.##LLLLLLLLLL
#L#L#L.L.##LL.L.LL#.#L#L##LLL#LLLL.#L#.#LL.LLLLLL.L#L#L.L#L#L#L#L#L#L#.LLLLLLL.#L#L#L.LLL#L#L#L#L#
LL#LLLL#.LLL#.#L#L#L#LLLLLL#.LL#L#.LLLLLL#.#L#L#L#L#L#L#LLLLLLLL.LLLLL.#L#L#.#.LL#L#L#L#LLL#LLLLLL
#...L#L...#....L......#..#....LL...#.#L#...............L..#L.#L#.#L..#..........L......L.#....#.##
LL#LLLL#.LLL#.#L#L#.#LLLLLL#.#L#L#.#.LLLL.#L#L#L#.#L#L#L#LLL#LLL.LL#LL#L#L#L#L#.#L#L#L#.LLLL#LLLLL
#LLLL#LL.##LL.LLLLL.LL#L#L.L.LLLLL.LL#.#LL.LLLLLL.LLLLL.LL#L.LL#.#LLLL.LLLLLLLLLLLL.L.#L#L#LLL#.L#
LL#LLLL#.LLL#.#.#L#.#LLLLLL#L#L#.#.#LLLLL#L##.#L#L#L#L#.#LLLLLLL..L.L#.##L#L#L#L#L#L#..L.LLLLLLLLL
#LLL##LL.L

In [41]:
(next_map == '#').sum()

2412

In [46]:
def count_unoccupied_expanded(curr_map, next_map, pos):
    state = curr_map[(pos)]
   
    def check_loc(ir, ic, pos):
        if (pos[0]+ir <0 or  pos[0]+ir >=r or
            pos[1]+ic <0 or  pos[1]+ic >=c 
           ):
            return False
        return True
        
    def search_further(ir, ic, pos):
        if not check_loc(ir,ic,pos):
            return 'B'
        
        step=1
        s_state =  curr_map[(pos[0]+ir*step,
                             pos[1]+ic*step)]
        
        while s_state == '.':
            step +=1
   
            if not check_loc(ir*step, ic*step, pos):
                return 'B'
            s_state =  curr_map[(pos[0]+ir*step,
                                 pos[1]+ic*step)]
                            
        return s_state
    
    n_occ = sum([ search_further(i,j ,pos) =='#'  
                  for i in [-1, 0, 1]
                  for j in  [-1, 0, 1]
                  if  (pos[0]+i  >= 0 and pos[0]+i  <  r
                       and not (i ==j == 0) and 
                       pos[1]+j  >= 0 and pos[1]+j  <  c)
                ])
    
    if state == 'L' and n_occ == 0 :
            next_map[pos] = "#"
            
    if state == '#' and n_occ >=5:
            next_map[pos] = "L"
            
    return next_map
        
cur_map = seats.copy()
diff=1
#for i in range(4):
iteration = 0
while diff != 0 and iteration < 500:
    next_map = cur_map.copy()
    for row in range(r):
        for col in range(c):
            if cur_map[(row,col)] == '.':
                continue
            next_map = count_unoccupied_expanded(cur_map, next_map, (row,col))
            
    diff = (next_map != cur_map).sum()
    iteration +=1
    cur_map = next_map.copy()
            

In [47]:
iteration

87

In [48]:
(next_map == '#').sum()

2176

# Day 12

In [5]:
import numpy as np

In [3]:
movements=[]

with open('input_day12.txt', 'r') as f:
    for line in f.readlines():
        movements.append((line[0], int(line[1:])))


In [6]:
np.array([0,1]) + np.array([0,1])

array([0, 2])

In [7]:
tmp=['a', 'b', 'c']

In [9]:
tmp.index('b')

1

In [13]:
-5%4

3

In [15]:
move={
    'N' : np.array([0,1]),
    'E' : np.array([1,0]),
    'S' : np.array([0,-1]),
    'W' : np.array([-1,0]),
}

compass = ['N', 'E', 'S', 'W']

def update_direction(direction, code, degrees):
    move = degrees//90
    move = move if code == 'R' else -1*move
    
    cur = compass.index(direction)
    return compass[(cur+move)%4]
    
    
direction= 'E'
pos = np.array([0,0])

for step in movements:
    if step[0] in ['R', 'L']:
        direction = update_direction(direction, step[0], step[1])
        continue
    
    move_dir = direction if step[0] == 'F' else step[0]
    pos += step[1]* move[move_dir]
        

pos

array([-863,  824])

In [16]:
abs(pos[0])+abs(pos[1])

1687

In [32]:
ship = np.array([0,0])
waypoint = np.array([10,1])

def turn_waypoint(waypoint, code, degrees):
    bearing = ('E' if waypoint[0] > 0 else 'W',
               'N' if waypoint[1] > 0 else 'S',
              )
    new_bearing = [update_direction(bearing[i], code, degrees) for i in range(2)]
    
    newpoint = move[new_bearing[0]]*np.abs(waypoint[0])  + move[new_bearing[1]]*np.abs(waypoint[1])
    return newpoint
    
for step in movements:
    if step[0] in ['R', 'L']:
        waypoint = turn_waypoint(waypoint, step[0], step[1])
        continue
        
    if step[0] == 'F':
        ship += step[1]*waypoint
    else:
        waypoint += step[1]* move[step[0]]

In [33]:
#32593 - is wrong
np.abs(ship).sum()

20873

# Day 13

In [26]:
import numpy as np

In [73]:
time_depart = 1002392
buses = '23,x,x,x,x,x,x,x,x,x,x,x,x,41,x,x,x,37,x,x,x,x,x,421,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,17,x,19,x,x,x,x,x,x,x,x,x,29,x,487,x,x,x,x,x,x,x,x,x,x,x,x,13'

In [2]:
ids = [ int(bus) for bus in buses.split(',') if bus !='x']

In [3]:
ids

[23, 41, 37, 421, 17, 19, 29, 487, 13]

In [4]:
time_to_wait=  [ i - time_depart%i for i in ids ]

In [5]:
time_to_wait

[17, 17, 12, 9, 13, 10, 22, 341, 12]

In [7]:
idx = time_to_wait.index(min(time_to_wait))

In [8]:
ids[idx]*time_to_wait[idx]

3789

In [74]:
#buses ='7,13,x,x,59,x,31,19'
bus_ids = [ (int(b),buses.split(',').index(b)) for b in buses.split(',')  if b!='x']

In [75]:
bus_ids

[(23, 0),
 (41, 13),
 (37, 17),
 (421, 23),
 (17, 40),
 (19, 42),
 (29, 52),
 (487, 54),
 (13, 67)]

In [100]:
time_x = 0
M=1
to=9
for idx,remainder in bus_ids[:to]: 
    M*=idx
    
for idx, remainder in bus_ids[:to]:
    ai = (idx - remainder%idx )%idx
    b =  int(M/idx)
    b_inv = pow(b, -1, idx)
    b_inv = b_inv%idx
    
    time_x += ai*b*b_inv
    

In [101]:
time_x %M

667437230788118

In [102]:
[ i - time_x%i for i in ids ]

[23, 13, 17, 23, 6, 4, 23, 54, 2]